version: '2.0'
services:
  frontend:
    build: ./frontend
    image: funny-links/frontend
    environment:
      - REACT_APP_BACKENDURL=http://localhost:5001
      - REACT_APP_FRONTENDURL=http://localhost:8003
    ports:
     - 8003:80
  backend:
    build: ./backend
    image: funny-links/backend
    volumes:
      - /Users/tobirohrer/:/analyse/
    ports:
     - 5001:8000