version: '2.0'
services:
  frontend:
    build: ./frontend
    image: funny-links/frontend
    environment:
      - REACT_APP_BACKENDURL=http://localhost:5001
    ports:
     - 8003:80
  backend:
    build: ./backend
    image: funny-links/backend
    volumes:
      - data:/Users/tobirohrer/git/remember-me/backend/store
    ports:
     - 5001:8000

volumes:
  data:
    driver: local
